version: "3"

services:
  phi-rank-query:
    image: ubuntu:latest
    working_dir: /app
    command: /app/phi-rank-query-linux-amd64
    volumes:
      - ./build:/app
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    ports:
      - "8542:8542"
    restart: always
    stdin_open: true
    tty: true
